#!/bin/bash

./bin/fluidIOP3D ./cfg/stam.64.iop.cfg
./bin/svdOutOfCoreMultiple ./cfg/stam.64.iop.cfg
./bin/cubatureGeneratorStamStaged ./cfg/stam.64.iop.cfg

./bin/buildProducts ./cfg/stam.64.iop.cfg
./bin/compressMatrices ./cfg/stam.64.iop.cfg | tee compressionIOPTimings.txt
./bin/reducedCompressedIOP3D ./cfg/stam.64.iop.cfg | tee reducedCompressedIOPTimings.txt

